version: 2
jobs:
  build:
    environment:
      MEDIA_DIR: media
    docker:
      - image: eulertour/manim:circleci
    steps:
      - checkout
      - run:
          command: python3 -m pytest mobject/test.py
