directories:
  # Set this to true if you want the path to video files
  # to match the directory structure of the path to the
  # sourcecode generating that video
  mirror_module_path: False
  # Manim may write to and read from teh file system, e.g.
  # to render videos and to look for svg/png assets. This
  # will specify where those assets live, with a base directory,
  # and various subdirectory names within it
  base: ""
  subdirs:
    # Where should manim output video and image files?
    output: "videos"
    # If you want to use images, manim will look to these folders to find them
    raster_images: "raster_images"
    vector_images: "vector_images"
    # If you want to use sounds, manim will look here to find it.
    sounds: "sounds"
    # Place for other forms of data relevant to any projects, like csv's
    data: "data"
    # When downloading, say an image, where will it go?
    downloads: "downloads"
  # For certain object types, especially Tex and Text, manim will save information
  # to file to prevent the need to re-compute, e.g. recompiling the latex. By default,
  # it stores this saved data to whatever directory appdirs.user_cache_dir("manim") returns,
  # but here a user can specify a different cache location
  cache: ""
window:
  # The position of window on screen. UR -> Upper Right, and likewise DL -> Down and Left,
  # UO would be upper middle, etc.
  position_string: UR
  # If using multiple monitors, which one should show the window
  monitor_index: 0
  # If not full screen, the default to give it half the screen width
  full_screen: False
  # Other optional specifications that override the above include:
  # position: (500, 500)  # Specific position, in pixel coordiantes, for upper right corner
  # size: (1920, 1080)  # Specific size, in pixels
camera:
  resolution: (1920, 1080)
  background_color: "#333333"
  fps: 30
  background_opacity: 1.0
file_writer:
  # If break_into_partial_movies is set to True, then many small
  # files will be written corresponding to each Scene.play and
  # Scene.wait call, and these files will then be combined
  # to form the full scene.  Sometimes video-editing is made
  # easier when working with the broken up scene, which
  # effectively has cuts at all the places you might want.
  break_into_partial_movies: False
  video_codec: "libx264"
  pixel_format: "yuv420p"
  saturation: 1.0
  gamma: 1.0
style:
  tex_template: "default"
  font: "Consolas"
  text_alignment: "LEFT"
embed:
  exception_mode: "Verbose"
resolution_options:
  # When the user passes in -l, -m, --hd or --uhd, these are the corresponding
  # resolutions
  low: (854, 480)
  med: (1280, 720)
  high: (1920, 1080)
  4k: (3840, 2160)
universal_import_line: "from manimlib import *"
ignore_manimlib_modules_on_reload: True
