directories:
  # Set this to true if you want the path to video files
  # to match the directory structure of the path to the
  # sourcecode generating that video
  mirror_module_path: False
  # Manim may write to and read from teh file system, e.g.
  # to render videos and to look for svg/png assets. This
  # will specify where those assets live, with a base directory,
  # and various subdirectory names within it
  base: ""
  subdirs:
    # Where should manim output video and image files?
    output: "videos"
    # If you want to use images, manim will look to these folders to find them
    raster_images: "raster_images"
    vector_images: "vector_images"
    # If you want to use sounds, manim will look here to find it.
    sounds: "sounds"
    # Place for other forms of data relevant to any projects, like csv's
    data: "data"
    # When downloading, say an image, where will it go?
    downloads: "downloads"
  # For certain object types, especially Tex and Text, manim will save information
  # to file to prevent the need to re-compute, e.g. recompiling the latex. By default,
  # it stores this saved data to whatever directory appdirs.user_cache_dir("manim") returns,
  # but here a user can specify a different cache location
  cache: ""
universal_import_line: "from manimlib import *"
style:
  tex_template: "default"
  font: "Consolas"
  text_alignment: "LEFT"
  background_color: "#333333"
# Set the position of preview window, you can use directions, e.g. UL/DR/OL/OO/...
# also, you can also specify the position(pixel) of the upper left corner of 
# the window on the monitor, e.g. "960,540"
window_position: UR
window_monitor: 0
full_screen: False
file_writer_config:
  # If break_into_partial_movies is set to True, then many small
  # files will be written corresponding to each Scene.play and
  # Scene.wait call, and these files will then be combined
  # to form the full scene.  Sometimes video-editing is made
  # easier when working with the broken up scene, which
  # effectively has cuts at all the places you might want.
  break_into_partial_movies: False
  video_codec: "libx264"
  pixel_format: "yuv420p"
  saturation: 1.0
  gamma: 1.0
camera_resolutions:
  low: "854x480"
  med: "1280x720"
  high: "1920x1080"
  4k: "3840x2160"
  default_resolution: "high"
fps: 30
embed_exception_mode: "Verbose"
embed_error_sound: False
